### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by remaerd** [jamma/cocos2d-typescript-definitions#3]
Hello,

I'm trying to use your definitions in WebStorm + TypeScript. And the IDE is complaining SAXParser, PlistParser and DirectorDelegate is missing. I'm new to Cocos2D and TypeScript and WebStorm so I have no idea what and how to solve the problems. Could you fix those problems?

Thank you.

**Comment by jamma** [comment]
Hey,

These definitions don't do anything other than give "hints" to the
TypeScript compiler. So any errors you see related to using this stuff can
be safely ignored. I created these definitions as part of the game that I'm
currently writing, and as such, I make fixes and and add new stuff as I
need it.

Please feel free to use these definitions as well make corrections and
additions, other users have already done so. The more people that
contribute, the better it will be. However, I don't really have the time
(nor the desire, to be completely honest) to take feature or bug requests.

If you have questions about how to make the fixes yourself, feel free to
ask. I'd be happy to help. Thanks!

**Comment by remaerd** [comment]
I discovered that I can do the same stuff with CoffeeScript with Auto Completion in WebStorm. So TypeScript definition is not required anymore. I'm familiar with CoffeeScript, it's a better choice for me.

It's seems like there's another Github repo which have many TypeScript Definitions in it. Maybe you can find more contributors in their program. https://github.com/DefinitelyTyped/DefinitelyTyped

Cheers.
